/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_gcsc_vrl_ug4_UG4 */

#ifndef _Included_edu_gcsc_vrl_ug4_UG4
#define _Included_edu_gcsc_vrl_ug4_UG4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_gcsc_vrl_ug4_UG4
 * Method:    helloUG
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_gcsc_vrl_ug4_UG4_helloUG
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
